# Generated by Django 5.2 on 2025-04-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='main.history')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answers')),
            ],
        ),
    ]
